### ISSUE TITLE
[Bug report] Config folder requires manual creation after yesterday's update

### ISSUE THREAD

**Issue by 0xfMel** [tinted-theming/base16-shell-legacy#13]
## Describe the bug

when settings a new theme with a fresh install, it attempts to create a symlink to $BASE_SHELL_COLORSCHEME_PATH, but the $BASE16_CONFIG_PATH directory doesn't yet exist, so it errors, and the theme won't be set next time the shell starts.

## Expected behavior

$BASE16_CONFIG_PATH directory to be created automatically, so the symlink is created successfully

**Comment by JamyGolden** [comment]
Thanks for reporting. Are you using fish shell? I've merged a fix for this https://github.com/base16-project/base16-shell/pull/14

**Comment by 0xfMel** [comment]
Yes I was using fish.
